name: Web Image

on:
    # We only have so many github minutes, so we use a manual trigger
    # instead of automatically building on every push in a pull request.
    workflow_dispatch:
    # Trigger on all pushes to main.
    push:
      branches:
        - main

permissions: {}

jobs:
    prepare:
        runs-on: ubuntu-24.04
        permissions: {}
        steps:
            - id: repository_name
              env:
                REPO_NAME: ${{ github.event.repository.name }}
              run: echo "lowercase_repo_name=${REPO_NAME,,}" >> "$GITHUB_OUTPUT"
            - id: repository_owner
              env:
                REPO_OWNER: ${{ github.repository_owner }}
              run: echo "lowercase_repo_owner=${REPO_OWNER,,}" >> "$GITHUB_OUTPUT"
        outputs:
            lowercase_repo_name: ${{ steps.repository_name.outputs.lowercase_repo_name }}
            lowercase_repo_owner: ${{ steps.repository_owner.outputs.lowercase_repo_owner }}

    build-web-client:
        runs-on: ubuntu-24.04
        needs: prepare
        permissions:
            contents: read
            packages: write
        env:
            IMAGE: ghcr.io/${{ needs.prepare.outputs.lowercase_repo_owner }}/${{ needs.prepare.outputs.lowercase_repo_name }}-web-client
            TAG: ${{ github.head_ref || github.ref_name }}
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                persist-credentials: false
            - name: Login to GitHub Container Registry
              uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build ${{ needs.prepare.outputs.lowercase_repo_name }}-web-client
              run: |
                docker build --platform linux/amd64 -t "$IMAGE:$TAG" -f docker/web/Dockerfile_web-client --cache-from "$IMAGE:main,$IMAGE:$TAG" --build-arg BUILDKIT_INLINE_CACHE=1 .
                docker push "$IMAGE:$TAG"
    build-web-server:
        runs-on: ubuntu-24.04
        needs: prepare
        permissions:
            contents: read
            packages: write
        env:
            IMAGE: ghcr.io/${{ needs.prepare.outputs.lowercase_repo_owner }}/${{ needs.prepare.outputs.lowercase_repo_name }}-web-server
            TAG: ${{ github.head_ref || github.ref_name }}
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                persist-credentials: false
            - name: Login to GitHub Container Registry
              uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build ${{ needs.prepare.outputs.lowercase_repo_name }}-web-server
              run: |
                docker build --platform linux/amd64 -t "$IMAGE:$TAG" -f docker/web/Dockerfile_web-server --cache-from "$IMAGE:main,$IMAGE:$TAG" --build-arg BUILDKIT_INLINE_CACHE=1 .
                docker push "$IMAGE:$TAG"
    build-web-image:
        needs: [prepare, build-web-client, build-web-server]
        runs-on: ubuntu-24.04
        permissions:
            contents: read
            packages: write
        env:
            NAMESPACE: ghcr.io/${{ needs.prepare.outputs.lowercase_repo_owner }}
            IMAGE_PREFIX: ${{ needs.prepare.outputs.lowercase_repo_name }}
            IMAGE: ghcr.io/${{ needs.prepare.outputs.lowercase_repo_owner }}/${{ needs.prepare.outputs.lowercase_repo_name }}-web
            TAG: ${{ github.head_ref || github.ref_name }}
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                persist-credentials: false
            - name: Login to GitHub Container Registry
              uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build ${{ needs.prepare.outputs.lowercase_repo_name }}-web-image
              run: |
                docker build --platform linux/amd64 -t "$IMAGE:$TAG" -f docker/web/Dockerfile_web --build-arg NAMESPACE="$NAMESPACE" --build-arg IMAGE_PREFIX="$IMAGE_PREFIX" --build-arg TAG="$TAG" --cache-from "$IMAGE:main,$IMAGE:$TAG" --build-arg BUILDKIT_INLINE_CACHE=1 .
                docker push "$IMAGE:$TAG"
